### ISSUE TITLE
Universal Function Handler

### ISSUE THREAD

**Issue by ac360** [serverless/stdlib-nodejs#10]
**Goals:**

* Create a single function handler for synchronous and asynchronous functions that works across all providers.
* Offer a better user experience.

**Comment by ac360** [comment]
Started [investigating this idea](https://github.com/serverless/examples/tree/master/serverless-rest-api/lib/utils/serverless) in a boilerplate project.  This is an experiment at the moment.  Highlights are:

* Synchronous handler
* `req` and `res` params with lots of useful data and methods

cc @mthenw

**Comment by mthenw** [comment]
@ac360 you assume that sync handler is always triggered by APIG (`req`, `res`) which is not always true. I would not assume that because in microservices architecture there can be many sync functions that are called by other functions and `req`/`res` pattern doesn't fit there.

**Comment by mthenw** [comment]
Closing this one as I created another issue with details

https://github.com/serverless/stdlib-nodejs/issues/11
