### ISSUE TITLE
Generic function handler

### ISSUE THREAD

**Issue by mthenw** [serverless/stdlib-nodejs#15]
# Generic handler

`handler(function(event, [context], callback){})` (or `λ(...)`) 

Arguments:

- `function(event, [context], callback)` - hander function. Function accepts following arguments:
  - event - any type - event payload,
  - context (optional) - object - additional info
  - callback - `function` - callback function result `callback(err, result)`.

```javascript
const stdlib = require('@serverless/stdlib')();

exports.userFunc = stdlib.handler((event, callback) => {
  callback(new Error('not implemented'))  
});
```

## Notes

- Ad https://github.com/serverless/stdlib-nodejs/issues/14#issuecomment-263906286 @dougmoscrop for now we will start with callback. I would like to have promise based version but we will start minimal.

- Ad https://github.com/serverless/stdlib-nodejs/issues/14#issuecomment-263904745 @ac360 context from global object is doable in AWS Lambda (because there is one execution per container). I'm not sure how this thing looks in GCF, Azure and IBM but it wouldn't assume that's true. So it's safer to have context object as a optional argument. Let me know what's your thoughts here.

> If you are writing truly portable functions, then wouldn't an optional argument require writing logic at the beginning of every function to check if context was passed in? 

Nope. Before calling user function we can check how many arguments it accepts and based on that we can pass 2 or 3 args.

```javascript
exports.userFunc = stdlib.handler((event, callback) => {
  callback(new Error('not implemented'))  
});

exports.userFunc = stdlib.handler((event, context, callback) => {
  callback(new Error('not implemented'))  
});

```

Both will work. No need to do `if`.

**Comment by mthenw** [comment]
I've been thinking about going full promise. It would be compatible with already existing `call` method.

Example handler could like like this:

```javascript
exports.userFunc = stdlib.handler((event) => {
  return do_some_stuff().then(() => {...})
});
```

**Comment by cometta** [comment]
may i know how to get req, resp parameter using this standard handler
