### ISSUE TITLE
OpenWhisk support

### ISSUE THREAD

**Issue by mthenw** [serverless/stdlib-nodejs#18]
https://github.com/openwhisk/openwhisk-client-js has a method for invoking other functions so we can implement it using that.

Few questions:

- how to distinguish AWS Lambda from OpenWhisk? The most reliable way is to check if there is `__OW_NAMESPACE` env (or any other specific to OW).
- is https://github.com/openwhisk/openwhisk-client-js included by default in environment?

CC @jthomas

**Comment by jthomas** [comment]
These are the environment variables available in the runtime.
https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md#accessing-action-metadata-within-the-action-body
Using the `NAMESPACE` is probably a good bet. 

The `openwhisk` module is included by default.
