### ISSUE TITLE
isColdStart method

### ISSUE THREAD

**Issue by flomotlik** [serverless/stdlib-nodejs#3]
To provide users with an easy way to track if something is a cold start we should provide a stable SDK method they can use.

```
sdk.isColdStart()
```

will return true the first time and false for any other invocations in that same deployed lambda.

**Comment by mthenw** [comment]
This one needs to wait for https://github.com/serverless/stdlib-nodejs/issues/10 because if there is no function that is called every time we can switch the toggle.
